### ISSUE TITLE
typo docker-compose.yaml at Workshop Complete

### ISSUE THREAD

**Issue by gleruzh** [CarlSargunar/Umbraco-Docker-Workshop#10]
case sensitive in string 8
```
context: ./Umbdata
```
should be
```
context: ./UmbData
```

**Comment by CarlSargunar** [comment]
Thanksfor submitting that PR - I'd spotted my self, but you beat me to correcting it :-)

Hope the course was useful for you

**Comment by gleruzh** [comment]
Yes, very useful. Thank you!
