### ISSUE TITLE
better SQL server check if running

### ISSUE THREAD

**Issue by Levvy055** [CarlSargunar/Umbraco-Docker-Workshop#11]
Sometimes MS SQL server takes more time to startup.

I found solution using this script: https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh

It can be used like that:
```
COPY ./wait-for-it.sh /wait-for-it.sh
RUN chmod +x wait-for-it.sh
```
And called in compose by:
`entrypoint: ["/wait-for-it.sh", "mydatabase:1433", "-t", "120", "--", "dotnet", "VirtoCommerce.Platform.Web.dll"]`

or something like that. Need to test it.

**Comment by CarlSargunar** [comment]
Thanks for the input - I think for the sake of simplicity I'm going to keep it as is, but I love the suggetion. In a production setting yours would be better, but for a workshop I'm happy with the basic implementation
