### ISSUE TITLE
Info about Umbraco 11 and Docker

### ISSUE THREAD

**Issue by afabri73** [CarlSargunar/Umbraco-Docker-Workshop#9]
Hi Carl,
I saw you at Codegarden 2022 - Containers and Umbraco
I'm a senior web developer and I'm planning to port the company intranet to Umbraco 11.
I work in an hospital and I would like your advice about our project to realize the corporate intranet with Umbraco 11.
So...the scenario would be to have 1 backoffice server (on windows server/IIS) and 2 frontends (no backoffice - docker/kubernetes)
Therefore I would like to know:
- if it is a valid configuration for an intranet
- If it could be stable and performing
- how to dockerize Umb 11
- how to config the 2 frontends
- how to manage sessions (DB?)
- if it is better to have media only in BO server
Thank you
Adriano

**Comment by afabri73** [comment]
Thank you Carl for the info and I just subscribed to the umbraco discord channel.
I tried to write to you with your website (https://carlcod.es/) but the contact form don't send the message (go in error when submit)

To be honest, I still hadn't analized Umbraco 12 in depth, but after what you told me it will be the first thing I'll do tomorrow together with your Umbraco Docker Workshop 😃

Thank you again and see you on discord 🤗👋

Adriano

**Comment by CarlSargunar** [comment]
He he - yeah, oops - I do need to fix my website. TBH, it's a very old umbraco 9 site, I need to update it to 11, I've just been too busy :-)

Hope the workshop helps you, but happy to chat - I'm usually on discord and if I can help I will

thanks
